export const SIGN_IN_REQUEST: 'SIGN_IN_REQUEST'  = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS' = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAILED: 'SIGN_IN_FAILED' = 'SIGN_IN_FAILED'

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS'
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED'

export const CHECK_AUTH: 'CHECK_AUTH' = 'CHECK_AUTH'

export const SIGN_UP_REQUEST: 'SIGN_UP_REQUEST' = 'SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS' = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILED: 'SIGN_UP_FAILED' = 'SIGN_UP_FAILED'

export const SIGN_OUT_REQUEST: 'SIGN_OUT_REQUEST' = 'SIGN_OUT_REQUEST'
export const SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS' = 'SIGN_OUT_SUCCESS'
export const SIGN_OUT_FAILED: 'SIGN_OUT_FAILED '  = 'SIGN_OUT_FAILED '

export const SAVE_DATA_REQUEST: 'SAVE_DATA_REQUEST' = 'SAVE_DATA_REQUEST'
export const SAVE_DATA_SUCCESS: 'SAVE_DATA_SUCCESS' = 'SAVE_DATA_SUCCESS'
export const SAVE_DATA_FAILED: 'SAVE_DATA_FAILED' = 'SAVE_DATA_FAILED'

export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED'

export const CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST' = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS' = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED' = 'CHANGE_PASSWORD_FAILED'


export const GET_INGREDIENTS_REQUEST: 'GET_INGREDIENTS_REQUEST' = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = 'GET_INGREDIENTS_FAILED'

export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT: 'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT'

export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED'

export const CLOSE_ORDER_MODAL: 'CLOSE_ORDER_MODAL' = 'CLOSE_ORDER_MODAL'

export const MOVE_INGREDIENT: 'MOVE_INGREDIENT' = 'MOVE_INGREDIENT'

export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_CONNECTION_DISCONNECT: 'WS_CONNECTION_DISCONNECT' = 'WS_CONNECTION_DISCONNECT'
